const B=document.getElementById('board'),S=document.getElementById('svg');let cs=[],ws=[],sel=null,start=null,next=1;
const info={battery:['🔋','Baterai',12,'V'],resistor:['▱','Resistor',6,'Ω'],lamp:['💡','Lampu',6,'Ω'],switch:['⏻','Saklar',0,'']};
document.querySelectorAll('.item').forEach(x=>x.ondragstart=e=>e.dataTransfer.setData('t',x.dataset.t));B.ondragover=e=>e.preventDefault();B.ondrop=e=>{let t=e.dataTransfer.getData('t'),r=B.getBoundingClientRect();if(t)add(t,e.clientX-r.left-57,e.clientY-r.top-34)};
function add(t,x,y,id){let q=info[t],c={id:id||next++,t,x:Math.max(5,x),y:Math.max(5,y),name:q[1]+' '+(cs.filter(a=>a.t==t).length+1),v:q[2],u:q[3],on:true};cs.push(c);render();pick(c.id)}
function get(id){return cs.find(c=>c.id==id)}function point(c,s){return{x:c.x+(s=='L'?0:115),y:c.y+34}}
function render(){document.querySelectorAll('.comp').forEach(e=>e.remove());document.getElementById('empty').style.display=cs.length?'none':'block';cs.forEach(c=>{let e=document.createElement('div');e.className='comp '+(sel==c.id?'sel ':'')+(c.t=='switch'&&c.on?'on':'')+(c.t=='lamp'&&c.on&&isOn()?'on':'');e.dataset.id=c.id;e.style.left=c.x+'px';e.style.top=c.y+'px';e.innerHTML=`<div class=head>${info[c.t][0]} ${c.name}</div><div class=val>${c.t=='switch'?(c.on?'ON':'OFF'):c.v+' '+c.u}</div><i class="term left" data-s=L></i><i class="term right" data-s=R></i>`;e.onclick=x=>{if(!x.target.classList.contains('term'))pick(c.id)};e.ondblclick=x=>{if(c.t=='switch'){c.on=!c.on;render();calculate()}};e.onpointerdown=x=>move(x,c);e.querySelectorAll('.term').forEach(z=>z.onclick=x=>{x.stopPropagation();terminal(c.id,z.dataset.s)});B.appendChild(e)});draw()}
function move(e,c){if(e.target.classList.contains('term'))return;e.preventDefault();let r=B.getBoundingClientRect(),ox=e.clientX-r.left-c.x,oy=e.clientY-r.top-c.y;let mv=x=>{let a=B.getBoundingClientRect();c.x=Math.max(3,Math.min(780,x.clientX-a.left-ox));c.y=Math.max(3,Math.min(510,x.clientY-a.top-oy));let z=document.querySelector(`[data-id="${c.id}"]`);z.style.left=c.x+'px';z.style.top=c.y+'px';draw()};let up=()=>{removeEventListener('pointermove',mv);removeEventListener('pointerup',up)};addEventListener('pointermove',mv);addEventListener('pointerup',up)}
function terminal(id,s){if(!start){start={id,s};mark(id,s,true);msg('Terminal dipilih. Klik terminal lain.');return}if(start.id==id){mark(id,s,false);start=null;return}if(!ws.some(w=>(w.a==start.id&&w.as==start.s&&w.b==id&&w.bs==s)||(w.b==start.id&&w.bs==start.s&&w.a==id&&w.as==s)))ws.push({a:start.id,as:start.s,b:id,bs:s});document.querySelectorAll('.term').forEach(x=>x.classList.remove('active'));start=null;draw();msg('Kabel berhasil dibuat.')}
function mark(id,s,v){document.querySelector(`[data-id="${id}"] .${s=='L'?'left':'right'}`).classList.toggle('active',v)}
function draw(){S.innerHTML='';ws.forEach(w=>{let a=point(get(w.a),w.as),b=point(get(w.b),w.bs),m=(a.x+b.x)/2,p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',`M${a.x} ${a.y} C${m} ${a.y},${m} ${b.y},${b.x} ${b.y}`);p.setAttribute('fill','none');p.setAttribute('stroke',isOn()?'#16834b':'#34495e');p.setAttribute('stroke-width','5');S.appendChild(p)})}
function pick(id){sel=id;render();let c=get(id);document.getElementById('none').hidden=true;document.getElementById('form').hidden=false;document.getElementById('title').textContent=info[c.t][0]+' '+c.name;document.getElementById('name').value=c.name;document.getElementById('value').value=c.v;document.getElementById('unit').value=c.u||'V';let no=c.t=='switch';document.getElementById('vl').style.display=no?'none':'block';document.getElementById('ul').style.display=no?'none':'block'}
function applyEdit(){let c=get(sel);if(!c)return;c.name=document.getElementById('name').value||c.name;if(c.t!='switch'){c.v=Math.max(.1,Number(document.getElementById('value').value)||1);c.u=document.getElementById('unit').value}render();calculate()}
function deleteSelected(){if(!sel)return;cs=cs.filter(c=>c.id!=sel);ws=ws.filter(w=>w.a!=sel&&w.b!=sel);sel=null;document.getElementById('none').hidden=false;document.getElementById('form').hidden=true;render();calculate()}
function clearBoard(){cs=[];ws=[];sel=null;render();calculate();msg('Papan dibersihkan.')}
function isOn(){return cs.some(c=>c.t=='switch'&&c.on)&&cs.some(c=>c.t=='battery')&&ws.length>0}
function msg(t){document.getElementById('msg').textContent=t}
function calculate(){let b=cs.find(c=>c.t=='battery'),load=cs.filter(c=>c.t=='resistor'||c.t=='lamp');document.getElementById('rv').textContent=b?b.v+' V':'-';if(!b||!load.length){document.getElementById('rr').textContent='-';document.getElementById('ri').textContent='0 A';document.getElementById('rt').textContent='-';return}let R=load.reduce((s,c)=>s+c.v,0);let I=isOn()?b.v/R:0;document.getElementById('rr').textContent=R.toFixed(2)+' Ω';document.getElementById('ri').textContent=I.toFixed(3)+' A';document.getElementById('rt').textContent='Seri / jalur tunggal';document.getElementById('explain').textContent='I = V/R. Nilai komponen dapat diubah. Untuk rangkaian paralel, susun cabang pada papan dan gunakan nilai masing-masing sebagai bahan pembelajaran.';render()}
render();calculate();